cluster.info.update.interval: 5m
cluster.name: es_1.server1
node.name: 1.es1
node.master: true
node.data: true
path.data: /data/elasticsearch
path.logs: /data/var/log/elasticsearch
bootstrap.memory_lock: true
bootstrap.system_call_filter: false
network.host: 0.0.0.0
discovery.zen.fd.ping_timeout: 60s
cluster.initial_master_nodes: ["1.es3", "1.es4", "1.es1", "1.es2"]

http.cors.enabled: true
http.cors.allow-origin: "*"
indices.memory.index_buffer_size: 20%
indices.breaker.request.limit: 50%
indices.breaker.fielddata.limit: 10%
indices.fielddata.cache.size: 10%
indices.memory.min_index_buffer_size: 64mb
script.allowed_types: inline,stored
thread_pool.write.queue_size: 200
thread_pool.write.size: 5
xpack.security.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
action.auto_create_index: -ailpha-securitylog*,-ailpha-securityevent*,-ailpha-securityalarm*,-ailpha-custom-alarm*,-ailpha-statistics*,+*

indices.memory.max_index_buffer_size: 1024mb

xpack.monitoring.collection.enabled: true
